FLEET_INFO = {
    "kurita": {
        "x": 32,
        "y": 98,
        "ships": [
            "Yamato", "Musashi", "Nagato", "Myoukou", "Haguro",
            "Takao", "Atago", "Choukai", "Maya", "Noshiro",
            "Shimakaze", "Okinami", "Hayashimo", "Asashimo", "Naganami",
            "Fujinami"
        ]
    },
    "suzuki": {
        "x": 32,
        "y": 489,
        "ships": [
            "Kongou", "Haruna", "Suzuya", "Kumano", "Tone",
            "Chikuma", "Yahagi", "Urakaze", "Isokaze", "Yukikaze",
            "Hamakaze", "Kiyoshimo", "Nowaki"
        ]
    },
    "nishimura": {
        "x": 32,
        "y": 802,
        "ships": [
            "Fusou", "Yamashiro", "Mogami", "Shigure", "Michishio",
            "Asagumo", "Yamagumo"
        ]
    },
    "shima": {
        "x": 732,
        "y": 163,
        "ships": [
            "Nachi", "Ashigara", "Aoba", "Abukuma", "Kinu",
            "Akebono", "Ushio", "Kasumi", "Shiranui", "Uranami",
            "Hatsushimo", "Hatsuharu", "Wakaba"
        ]
    },
    "ozawa": {
        "x": 732,
        "y": 641,
        "ships": [
            "Zuikaku", "Chitose", "Chiyoda", "Zuihou", "Ise",
            "Hyuuga", "Tama", "Isuzu", "Ooyodo", "Akizuki",
            "Hatsuzuki"
        ]
    }
}

# Portrait information
PORTRAIT_WIDTH = 125
PORTRAIT_HEIGHT = 76
PORTRAIT_SPACING_HORIZONTAL = 2
PORTRAIT_SPACING_VERTICAL = 4

# Marker/overlay information
# These aren't really all that accurate; it's more of a basic outline
# It doesn't take into account non-remodeled ships that can remodel, etc.
MARKER_OPACITY = 175                                     # Set this to 0 if you don't want the overlays
MARKER_DONT_HAVE = (0, 0, 0, MARKER_OPACITY)             # Black - Don't have
MARKER_NOT_USABLE = (255, 0, 0, MARKER_OPACITY)          # Red, 1 - 25
MARKER_ALMOST_UNUSABLE = (255, 106, 0, MARKER_OPACITY)   # Orange, 26 - 40
MARKER_PROBABLY_USEABLE = (255, 216, 0, MARKER_OPACITY)  # Yellow, 41 - 64
MARKER_SUFFICIENT = (0, 226, 30, MARKER_OPACITY)         # Green, 65 - 99
MARKER_MARRIED = (255, 0, 220, MARKER_OPACITY)           # Pink, 99+

# https://github.com/TeamFleet/WhoCallsTheFleet-DB/blob/master/db/ships.nedb
SHIP_DB = {
    "174": ["Z1", ""],
    "158": ["川内", "sendai"],
    "144": ["夕立", "yuudachi"],
    "511": ["Гангут", ""],
    "86": ["比叡", "hiei"],
    "97": ["満潮", "michishio"],
    "38": ["初春", "hatsuharu"],
    "251": ["荒潮", "arashio"],
    "356": ["鹿島", "kashima"],
    "27": ["山城", "yamashiro"],
    "231": ["曙", "akebono"],
    "36": ["雷", "ikazuchi"],
    "77": ["伊勢", "ise"],
    "1": ["睦月", "mutsuki"],
    "63": ["那智", "nachi"],
    "403": ["伊401", "I-401"],
    "271": ["摩耶", "maya"],
    "475": ["旗風", "hatakaze"],
    "101": ["木曾", "kiso"],
    "186": ["時津風", "tokitsukaze"],
    "160": ["那珂", "naka"],
    "303": ["巻雲", "makigumo"],
    "457": ["山風", "yamakaze"],
    "498": ["村雨", "murasame"],
    "136": ["大和", "yamato"],
    "130": ["熊野", "kumano"],
    "189": ["筑摩", "chikuma"],
    "216": ["多摩", "tama"],
    "17": ["陽炎", "kagerou"],
    "40": ["若葉", "wakaba"],
    "94": ["漣", "sazanami"],
    "180": ["Z3", ""],
    "132": ["秋雲", "akigumo"],
    "237": ["電", "inazuma"],
    "400": ["伊8", "I-8"],
    "359": ["沖波", "okinami"],
    "525": ["松輪", "matsuwa"],
    "173": ["Bismarck", ""],
    "201": ["吹雪", "fubuki"],
    "254": ["睦月", "mutsuki"],
    "84": ["加賀", "kaga"],
    "125": ["熊野", "kumano"],
    "393": ["Ark Royal", ""],
    "503": ["鈴谷", "suzuya"],
    "133": ["夕雲", "yuugumo"],
    "127": ["伊58", "I-58"],
    "489": ["満潮", "michishio"],
    "402": ["まるゆ", "maruyu"],
    "108": ["千歳", "chitose"],
    "123": ["衣笠", "kinugasa"],
    "100": ["多摩", "tama"],
    "284": ["隼鷹", "junyou"],
    "176": ["Prinz Eugen", ""],
    "424": ["高波", "takanami"],
    "404": ["雲龍", "unryuu"],
    "390": ["天霧", "amagiri"],
    "12": ["磯波", "isonami"],
    "246": ["五月雨", "samidare"],
    "54": ["川内", "sendai"],
    "43": ["時雨", "shigure"],
    "236": ["雷", "ikazuchi"],
    "154": ["香取", "katori"],
    "163": ["まるゆ", "maruyu"],
    "411": ["扶桑", "fusou"],
    "345": ["高波", "takanami"],
    "488": ["由良", "yura"],
    "256": ["皐月", "satsuki"],
    "235": ["響", "hibiki"],
    "19": ["黒潮", "kuroshio"],
    "76": ["龍驤", "ryuujou"],
    "532": ["涼月", "suzutsuki"],
    "207": ["綾波", "ayanami"],
    "82": ["伊勢", "ise"],
    "30": ["菊月", "kikuzuki"],
    "60": ["加古", "kako"],
    "524": ["択捉", "etorofu"],
    "15": ["曙", "akebono"],
    "432": ["Graf Zeppelin", ""],
    "14": ["敷波", "shikinami"],
    "500": ["神威", "kamoi"],
    "353": ["Graf Zeppelin", ""],
    "429": ["天城", "amagi"],
    "288": ["翔鶴", "shoukaku"],
    "91": ["飛龍", "hiryuu"],
    "275": ["長門", "nagato"],
    "398": ["伊168", "i-168"],
    "462": ["瑞鶴", "zuikaku"],
    "111": ["瑞鶴", "zuikaku"],
    "529": ["大鹰", "taiyou"],
    "149": ["金剛", "kongou"],
    "499": ["神威", "kamoi"],
    "182": ["明石", "akashi"],
    "455": ["萩風", "hagikaze"],
    "59": ["古鷹", "furutaka"],
    "443": ["Libeccio", ""],
    "465": ["鹿島", "kashima"],
    "203": ["初雪", "hatsuyuki"],
    "47": ["涼風", "suzukaze"],
    "37": ["電", "inazuma"],
    "450": ["秋津洲", "akitsushima"],
    "274": ["筑摩", "chikuma"],
    "177": ["Prinz Eugen", ""],
    "109": ["千代田", "chiyoda"],
    "518": ["国後", "kunashiri"],
    "196": ["飛龍", "hiryuu"],
    "297": ["千代田", "chiyoda"],
    "155": ["伊401", "I-401"],
    "531": ["佐渡", "sado"],
    "293": ["夕張", "yuubari"],
    "473": ["春風", "harukaze"],
    "330": ["秋月", "akizuki"],
    "480": ["狭霧", "sagiri"],
    "418": ["皐月", "satsuki"],
    "66": ["高雄", "takao"],
    "384": ["松輪", "matsuwa"],
    "281": ["龍驤", "ryuujou"],
    "312": ["浜風", "hamakaze"],
    "459": ["江風", "kawakaze"],
    "88": ["日向", "hyuuga"],
    "347": ["Libeccio", ""],
    "515": ["Ark Royal", ""],
    "267": ["足柄", "ashigara"],
    "81": ["陸奥", "mutsu"],
    "324": ["早霜", "hayashimo"],
    "29": ["文月", "fumizuki"],
    "262": ["古鷹", "furutaka"],
    "71": ["利根", "tone"],
    "469": ["江風", "kawakaze"],
    "295": ["衣笠", "kinugasa"],
    "493": ["伊400", "I-400"],
    "458": ["海風", "umikaze"],
    "16": ["潮", "ushio"],
    "287": ["山城", "yamashiro"],
    "343": ["香取", "katori"],
    "230": ["朧", "oboro"],
    "217": ["木曾", "kiso"],
    "197": ["蒼龍", "souryuu"],
    "126": ["伊168", "i-168"],
    "545": ["Saratoga", ""],
    "316": ["天津風", "amatsukaze"],
    "137": ["阿賀野", "agano"],
    "328": ["山雲", "yamagumo"],
    "417": ["加古", "kako"],
    "348": ["瑞穂", "mizuho"],
    "211": ["榛名", "haruna"],
    "64": ["足柄", "ashigara"],
    "399": ["伊58", "I-58"],
    "372": ["Commandant Teste", ""],
    "118": ["大井", "ooi"],
    "320": ["磯風", "isokaze"],
    "322": ["時津風", "tokitsukaze"],
    "302": ["夕雲", "yuugumo"],
    "107": ["千代田", "chiyoda"],
    "122": ["舞風", "maikaze"],
    "41": ["初霜", "hatsushimo"],
    "423": ["初月", "hatsuzuki"],
    "93": ["朧", "oboro"],
    "51": ["天龍", "tenryuu"],
    "170": ["浜風", "hamakaze"],
    "387": ["旗風", "hatakaze"],
    "243": ["時雨", "shigure"],
    "508": ["鈴谷", "suzuya"],
    "420": ["叢雲", "murakumo"],
    "313": ["谷風", "tanikaze"],
    "6": ["長月", "nagatsuki"],
    "321": ["大淀", "ooyodo"],
    "463": ["朝潮", "asashio"],
    "220": ["由良", "yura"],
    "245": ["夕立", "yuudachi"],
    "367": ["伊26", "I-26"],
    "32": ["初雪", "hatsuyuki"],
    "491": ["Commandant Teste", ""],
    "419": ["初霜", "hatsushimo"],
    "206": ["磯波", "isonami"],
    "509": ["熊野", "kumano"],
    "468": ["朝潮", "asashio"],
    "142": ["衣笠", "kinugasa"],
    "57": ["大井", "ooi"],
    "58": ["北上", "kitakami"],
    "408": ["隼鷹", "junyou"],
    "161": ["あきつ丸", "akitsu maru"],
    "446": ["Italia", ""],
    "478": ["龍田", "tatsuta"],
    "105": ["千代田", "chiyoda"],
    "543": ["長波", "naganami"],
    "70": ["最上", "mogami"],
    "239": ["子日", "nenohi"],
    "264": ["青葉", "aoba"],
    "439": ["Warspite", ""],
    "444": ["Aquila", ""],
    "139": ["矢矧", "yahagi"],
    "13": ["綾波", "ayanami"],
    "454": ["嵐", "arashi"],
    "25": ["北上", "kitakami"],
    "319": ["妙高", "myoukou"],
    "548": ["文月", "fumizuki"],
    "286": ["扶桑", "fusou"],
    "266": ["那智", "nachi"],
    "224": ["那珂", "naka"],
    "277": ["赤城", "akagi"],
    "214": ["龍田", "tatsuta"],
    "496": ["Zara", ""],
    "238": ["初春", "hatsuharu"],
    "221": ["名取", "natori"],
    "383": ["択捉", "etorofu"],
    "344": ["朝霜", "asashimo"],
    "195": ["綾波", "ayanami"],
    "46": ["五月雨", "samidare"],
    "253": ["霞", "kasumi"],
    "229": ["島風", "shimakaze"],
    "208": ["敷波", "shikinami"],
    "273": ["利根", "tone"],
    "240": ["若葉", "wakaba"],
    "99": ["球磨", "kuma"],
    "541": ["長門", "nagato"],
    "373": ["藤波", "fujinami"],
    "152": ["霧島", "kirishima"],
    "95": ["朝潮", "asashio"],
    "504": ["熊野", "kumano"],
    "485": ["藤波", "fujinami"],
    "156": ["大鳳", "taihou"],
    "72": ["筑摩", "chikuma"],
    "430": ["葛城", "katsuragi"],
    "416": ["古鷹", "furutaka"],
    "146": ["木曾", "kiso"],
    "361": ["Pola", ""],
    "369": ["山風", "yamakaze"],
    "78": ["金剛", "kongou"],
    "461": ["翔鶴", "shoukaku"],
    "282": ["祥鳳", "shouhou"],
    "242": ["白露", "shiratsuyu"],
    "435": ["如月", "kisaragi"],
    "449": ["Pola", ""],
    "606": ["伊400", "I-400"],
    "165": ["卯月", "uzuki"],
    "308": ["弥生", "yayoi"],
    "83": ["赤城", "akagi"],
    "69": ["鳥海", "choukai"],
    "362": ["親潮", "oyashio"],
    "530": ["伊504", ""],
    "31": ["望月", "mochizuki"],
    "332": ["葛城", "katsuragi"],
    "272": ["鳥海", "choukai"],
    "213": ["天龍", "tenryuu"],
    "129": ["鈴谷", "suzuya"],
    "415": ["野分", "nowaki"],
    "18": ["不知火", "shiranui"],
    "171": ["Bismarck", ""],
    "364": ["Warspite", ""],
    "517": ["占守", "shimusyu"],
    "9181": ["イオナ", "iona"],
    "106": ["千歳", "chitose"],
    "495": ["伊14", "I-14"],
    "79": ["榛名", "haruna"],
    "22": ["五十鈴", "isuzu"],
    "300": ["初風", "hatsukaze"],
    "279": ["蒼龍", "souryuu"],
    "11": ["深雪", "miyuki"],
    "268": ["羽黒", "haguro"],
    "192": ["那智", "nachi"],
    "550": ["Saratoga", ""],
    "346": ["照月", "teruzuki"],
    "414": ["山雲", "yamagumo"],
    "178": ["Bismarck", ""],
    "490": ["荒潮", "arashio"],
    "96": ["大潮", "ooshio"],
    "476": ["神風", "kamikaze"],
    "401": ["伊19", "I-19"],
    "380": ["大鹰", "taiyou"],
    "85": ["霧島", "kirishima"],
    "193": ["足柄", "ashigara"],
    "103": ["千代田", "chiyoda"],
    "326": ["初春", "hatsuharu"],
    "112": ["瑞鶴", "zuikaku"],
    "232": ["漣", "sazanami"],
    "124": ["鈴谷", "suzuya"],
    "185": ["龍鳳", "ryuuhou"],
    "9": ["吹雪", "fubuki"],
    "392": ["Richelieu", ""],
    "426": ["吹雪", "fubuki"],
    "547": ["多摩", "tama"],
    "223": ["神通", "jintsuu"],
    "540": ["対馬", "tsushima"],
    "294": ["舞風", "maikaze"],
    "260": ["三日月", "mikazuki"],
    "131": ["大和", "yamato"],
    "135": ["長波", "naganami"],
    "252": ["霰", "arare"],
    "56": ["那珂", "naka"],
    "10": ["白雪", "shirayuki"],
    "370": ["朝風", "asakaze"],
    "26": ["扶桑", "fusou"],
    "49": ["霞", "kasumi"],
    "445": ["秋津洲", "akitsushima"],
    "309": ["卯月", "uzuki"],
    "349": ["風雲", "kazagumo"],
    "472": ["朝風", "asakaze"],
    "265": ["妙高", "myoukou"],
    "296": ["千歳", "chitose"],
    "304": ["長波", "naganami"],
    "255": ["如月", "kisaragi"],
    "52": ["龍田", "tatsuta"],
    "183": ["大淀", "ooyodo"],
    "209": ["金剛", "kongou"],
    "241": ["初霜", "hatsushimo"],
    "219": ["五十鈴", "isuzu"],
    "234": ["暁", "akatsuki"],
    "92": ["隼鷹", "junyou"],
    "331": ["天城", "amagi"],
    "258": ["長月", "nagatsuki"],
    "249": ["大潮", "ooshio"],
    "407": ["潮", "ushio"],
    "325": ["清霜", "kiyoshimo"],
    "280": ["飛龍", "hiryuu"],
    "205": ["叢雲", "murakumo"],
    "431": ["U-511", ""],
    "166": ["あきつ丸", "akitsu maru"],
    "460": ["速吸", "hayasui"],
    "184": ["大鯨", "taigei"],
    "467": ["瑞鶴", "zuikaku"],
    "98": ["荒潮", "arashio"],
    "164": ["弥生", "yayoi"],
    "68": ["摩耶", "maya"],
    "181": ["天津風", "amatsukaze"],
    "440": ["Iowa", ""],
    "75": ["飛鷹", "hiyou"],
    "244": ["村雨", "murasame"],
    "537": ["涼月", "suzutsuki"],
    "80": ["長門", "nagato"],
    "62": ["妙高", "myoukou"],
    "327": ["朝雲", "asagumo"],
    "421": ["秋月", "akizuki"],
    "39": ["子日", "nenohi"],
    "33": ["叢雲", "murakumo"],
    "187": ["明石", "akashi"],
    "114": ["阿武隈", "abukuma"],
    "148": ["武蔵", "musashi"],
    "289": ["鬼怒", "kinu"],
    "352": ["速吸", "hayasui"],
    "386": ["対馬", "tsushima"],
    "391": ["狭霧", "sagiri"],
    "447": ["Roma", ""],
    "464": ["霞", "kasumi"],
    "35": ["響", "hibiki"],
    "143": ["武蔵", "musashi"],
    "427": ["鳥海", "choukai"],
    "434": ["睦月", "mutsuki"],
    "355": ["萩風", "hagikaze"],
    "159": ["神通", "jintsuu"],
    "513": ["Гангут", ""],
    "438": ["Saratoga", ""],
    "605": ["Luigi Torelli", ""],
    "310": ["Z1", ""],
    "368": ["浦波", "uranami"],
    "351": ["江風", "kawakaze"],
    "360": ["Iowa", ""],
    "42": ["白露", "shiratsuyu"],
    "406": ["雲龍", "unryuu"],
    "250": ["満潮", "michishio"],
    "116": ["瑞鳳", "zuihou"],
    "7": ["三日月", "mikazuki"],
    "153": ["大鳳", "taihou"],
    "494": ["伊13", "I-13"],
    "437": ["暁", "akatsuki"],
    "200": ["阿武隈", "abukuma"],
    "50": ["島風", "shimakaze"],
    "120": ["三隈", "mikuma"],
    "301": ["秋雲", "akigumo"],
    "413": ["朝雲", "asagumo"],
    "202": ["白雪", "shirayuki"],
    "48": ["霰", "arare"],
    "228": ["雪風", "yukikaze"],
    "376": ["占守", "shimusyu"],
    "20": ["雪風", "yukikaze"],
    "479": ["天霧", "amagiri"],
    "45": ["夕立", "yuudachi"],
    "291": ["千歳", "chitose"],
    "470": ["霞", "kasumi"],
    "215": ["球磨", "kuma"],
    "34": ["暁", "akatsuki"],
    "452": ["沖波", "okinami"],
    "412": ["山城", "yamashiro"],
    "2": ["如月", "kisaragi"],
    "226": ["不知火", "shiranui"],
    "102": ["千歳", "chitose"],
    "526": ["大鹰", "taiyou"],
    "162": ["神威", "kamoi"],
    "261": ["望月", "mochizuki"],
    "169": ["谷風", "tanikaze"],
    "204": ["深雪", "miyuki"],
    "481": ["水無月", "minazuki"],
    "405": ["春雨", "harusame"],
    "334": ["U-511", ""],
    "487": ["鬼怒", "kinu"],
    "314": ["酒匂", "sakawa"],
    "521": ["春日丸", "kasugamaru"],
    "145": ["時雨", "shigure"],
    "172": ["Bismarck", ""],
    "210": ["比叡", "hiei"],
    "150": ["比叡", "hiei"],
    "222": ["川内", "sendai"],
    "248": ["朝潮", "asashio"],
    "358": ["Zara", ""],
    "436": ["呂500", "ro-500"],
    "151": ["榛名", "haruna"],
    "89": ["鳳翔", "houshou"],
    "290": ["阿武隈", "abukuma"],
    "425": ["朝霜", "asashimo"],
    "140": ["酒匂", "sakawa"],
    "305": ["阿賀野", "agano"],
    "375": ["伊14", "I-14"],
    "233": ["潮", "ushio"],
    "292": ["千代田", "chiyoda"],
    "115": ["夕張", "yuubari"],
    "433": ["Saratoga", ""],
    "24": ["大井", "ooi"],
    "227": ["黒潮", "kuroshio"],
    "474": ["松風", "matsukaze"],
    "87": ["日向", "hyuuga"],
    "428": ["摩耶", "maya"],
    "311": ["Z3", ""],
    "269": ["高雄", "takao"],
    "357": ["初月", "hatsuzuki"],
    "486": ["浦波", "uranami"],
    "377": ["国後", "kunashiri"],
    "179": ["Z1", ""],
    "270": ["愛宕", "atago"],
    "259": ["菊月", "kikuzuki"],
    "175": ["Z3", ""],
    "318": ["龍鳳", "ryuuhou"],
    "385": ["佐渡", "sado"],
    "512": ["Октябрьская революция", ""],
    "21": ["長良", "nagara"],
    "157": ["龍驤", "ryuujou"],
    "65": ["羽黒", "haguro"],
    "306": ["能代", "noshiro"],
    "466": ["翔鶴", "shoukaku"],
    "113": ["鬼怒", "kinu"],
    "9182": ["タカオ", "takao"],
    "194": ["羽黒", "haguro"],
    "283": ["飛鷹", "hiyou"],
    "55": ["神通", "jintsuu"],
    "371": ["松風", "matsukaze"],
    "422": ["照月", "teruzuki"],
    "366": ["水無月", "minazuki"],
    "471": ["神風", "kamikaze"],
    "121": ["三隈", "mikuma"],
    "138": ["能代", "noshiro"],
    "67": ["愛宕", "atago"],
    "483": ["伊26", "I-26"],
    "188": ["利根", "tone"],
    "191": ["伊19", "I-19"],
    "442": ["Roma", ""],
    "456": ["親潮", "oyashio"],
    "9183": ["ハルナ", "haruna"],
    "247": ["涼風", "suzukaze"],
    "141": ["五十鈴", "isuzu"],
    "73": ["最上", "mogami"],
    "363": ["春風", "harukaze"],
    "365": ["Aquila", ""],
    "212": ["霧島", "kirishima"],
    "199": ["大潮", "ooshio"],
    "128": ["伊8", "I-8"],
    "74": ["祥鳳", "shouhou"],
    "278": ["加賀", "kaga"],
    "110": ["翔鶴", "shoukaku"],
    "23": ["由良", "yura"],
    "441": ["Littorio", ""],
    "409": ["早霜", "hayashimo"],
    "117": ["瑞鳳", "zuihou"],
    "167": ["磯風", "isokaze"],
    "90": ["蒼龍", "souryuu"],
    "147": ["Верный", ""],
    "323": ["春雨", "harusame"],
    "451": ["瑞穂", "mizuho"],
    "61": ["青葉", "aoba"],
    "257": ["文月", "fumizuki"],
    "44": ["村雨", "murasame"],
    "285": ["鳳翔", "houshou"],
    "190": ["初風", "hatsukaze"],
    "350": ["海風", "umikaze"],
    "453": ["風雲", "kazagumo"],
    "168": ["浦風", "urakaze"],
    "329": ["野分", "nowaki"],
    "535": ["Luigi Torelli", ""],
    "448": ["Zara", ""],
    "134": ["巻雲", "makigumo"],
    "225": ["陽炎", "kagerou"],
    "492": ["Richelieu", ""],
    "317": ["浦風", "urakaze"],
    "410": ["清霜", "kiyoshimo"],
    "374": ["伊13", "I-13"],
    "119": ["北上", "kitakami"],
    "263": ["加古", "kako"],
    "28": ["皐月", "satsuki"],
    "104": ["千歳", "chitose"],
    "307": ["矢矧", "yahagi"],
    "276": ["陸奥", "mutsu"],
    "53": ["名取", "natori"],
    "354": ["嵐", "arashi"],
    "539": ["UIT-25", ""],
    "218": ["長良", "nagara"] 
}